site:
  title: "Static-blogging-system"
  subtitle: "一个优雅的静态博客系统"
  url: "http://localhost:3000"
  author: "Your Name"
  email: "your.email@example.com"
  description: "一个基于 Node.js 的静态博客系统，支持 Markdown 和 LaTeX"
  keywords: "blog, static-site, markdown, node, express, ejs"
  language: "zh-CN"
  timezone: "Asia/Shanghai"
  theme: "default"  # 可选主题: default(简约现代), vintage(复古), tech(科技), minimal(极简), nature(自然)

nav:
  - name: "首页"
    url: "/"
  - name: "关于"
    url: "/about"
  - name: "联系"
    url: "/contact"

social:
  github: "https://github.com/yourusername"
  twitter: "https://twitter.com/yourusername"
  email: "your.email@example.com"